services:
  kc-db:
    image: postgres:15
    container_name: kc-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - kc_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak-local
    restart: unless-stopped
    command: start-dev --import-realm
    env_file:
      - ./.env
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://kc-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"

      KC_SPI_THEME_CACHE_THEMES: "false"
      KC_SPI_THEME_CACHE_TEMPLATES: "false"

      KC_SPI_EMAIL_TEMPLATE_PROVIDER: "rabbitmq"
      KC_SPI_EMAIL_TEMPLATE_RABBITMQ_RABBIT_HOST: "${RABBIT_HOST:-localhost}"
      KC_SPI_EMAIL_TEMPLATE_RABBITMQ_RABBIT_PORT: "${RABBIT_PORT:-5672}"
      KC_SPI_EMAIL_TEMPLATE_RABBITMQ_RABBIT_USERNAME: "${RABBIT_USER:-user}"
      KC_SPI_EMAIL_TEMPLATE_RABBITMQ_RABBIT_PASSWORD: "${RABBIT_PASS:-password}"
      KC_SPI_EMAIL_TEMPLATE_RABBITMQ_RABBIT_VIRTUAL_HOST: "${RABBIT_VHOST:-/}"
      KC_SPI_EMAIL_TEMPLATE_RABBITMQ_RABBIT_EXCHANGE: "${RABBIT_EXCHANGE:-notification.exchange}"
      KC_SPI_EMAIL_TEMPLATE_RABBITMQ_RABBIT_ROUTING_KEY: "${RABBIT_ROUTING_KEY:-digao.auth.email.reset-password}"
      KC_SPI_EMAIL_TEMPLATE_RABBITMQ_RABBIT_SSL: "${RABBIT_SSL:-false}"
      KC_SPI_EMAIL_TEMPLATE_RABBITMQ_RABBIT_CONNECTION_TIMEOUT_MS: "${RABBIT_CONN_TIMEOUT_MS:-10000}"
    depends_on:
      - kc-db
    ports:
      - "8080:8080"
    volumes:
    - ./realms:/opt/keycloak/data/import
    - ./themes:/opt/keycloak/themes
    - /Users/rodrigosiqueira/Documents/development/studies/solo/homelab-services/digao-keycloak-email-spi/target/digao-keycloak-email-spi-0.0.1-SNAPSHOT.jar:/opt/keycloak/providers/digao-keycloak-email-spi.jar

volumes:
  kc_pg_data:
